| schemaname | tablename       | indexname                      | indexdef                                                                                                                                                        |
| ---------- | --------------- | ------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| public     | collections_log | idx_collections_customer       | CREATE INDEX idx_collections_customer ON public.collections_log USING btree (customer_id)                                                                       |
| public     | collections_log | idx_collections_customer_id    | CREATE INDEX idx_collections_customer_id ON public.collections_log USING btree (customer_id) WHERE (customer_id IS NOT NULL)                                    |
| public     | collections_log | idx_collections_customer_name  | CREATE INDEX idx_collections_customer_name ON public.collections_log USING btree (customer_name)                                                                |
| public     | collections_log | idx_collections_date           | CREATE INDEX idx_collections_date ON public.collections_log USING btree (date)                                                                                  |
| public     | collections_log | idx_collections_payment_method | CREATE INDEX idx_collections_payment_method ON public.collections_log USING btree (payment_method)                                                              |
| public     | customers       | idx_customers_last_order       | CREATE INDEX idx_customers_last_order ON public.customers USING btree (last_order_date DESC) WHERE (last_order_date IS NOT NULL)                                |
| public     | customers       | idx_customers_name             | CREATE INDEX idx_customers_name ON public.customers USING btree (name)                                                                                          |
| public     | customers       | idx_customers_phone            | CREATE INDEX idx_customers_phone ON public.customers USING btree (phone) WHERE (phone IS NOT NULL)                                                              |
| public     | expenses        | idx_expenses_date              | CREATE INDEX idx_expenses_date ON public.expenses USING btree (date)                                                                                            |
| public     | expenses        | idx_expenses_is_fixed_date     | CREATE INDEX idx_expenses_is_fixed_date ON public.expenses USING btree (is_fixed, date DESC)                                                                    |
| public     | expenses        | idx_expenses_job_link          | CREATE INDEX idx_expenses_job_link ON public.expenses USING btree (job_link) WHERE (job_link IS NOT NULL)                                                       |
| public     | expenses        | idx_expenses_type              | CREATE INDEX idx_expenses_type ON public.expenses USING btree (expense_type)                                                                                    |
| public     | inventory       | idx_inventory_category         | CREATE INDEX idx_inventory_category ON public.inventory USING btree (category)                                                                                  |
| public     | inventory       | idx_inventory_date             | CREATE INDEX idx_inventory_date ON public.inventory USING btree (date)                                                                                          |
| public     | inventory       | idx_inventory_low_stock        | CREATE INDEX idx_inventory_low_stock ON public.inventory USING btree (quantity_left, reorder_level) WHERE (quantity_left <= reorder_level)                      |
| public     | inventory       | idx_inventory_test             | CREATE INDEX idx_inventory_test ON public.inventory USING btree (date DESC)                                                                                     |
| public     | sales_summary   | idx_sales_balance              | CREATE INDEX idx_sales_balance ON public.sales_summary USING btree (balance) WHERE (balance > (0)::numeric)                                                     |
| public     | sales_summary   | idx_sales_customer             | CREATE INDEX idx_sales_customer ON public.sales_summary USING btree (customer_id)                                                                               |
| public     | sales_summary   | idx_sales_customer_id          | CREATE INDEX idx_sales_customer_id ON public.sales_summary USING btree (customer_id) WHERE (customer_id IS NOT NULL)                                            |
| public     | sales_summary   | idx_sales_customer_name        | CREATE INDEX idx_sales_customer_name ON public.sales_summary USING btree (customer_name)                                                                        |
| public     | sales_summary   | idx_sales_date                 | CREATE INDEX idx_sales_date ON public.sales_summary USING btree (date)                                                                                          |
| public     | sales_summary   | idx_sales_job_id               | CREATE INDEX idx_sales_job_id ON public.sales_summary USING btree (sewing_job_id) WHERE (sewing_job_id IS NOT NULL)                                             |
| public     | sewing_jobs     | idx_jobs_customer_id           | CREATE INDEX idx_jobs_customer_id ON public.sewing_jobs USING btree (customer_id) WHERE (customer_id IS NOT NULL)                                               |
| public     | sewing_jobs     | idx_jobs_date                  | CREATE INDEX idx_jobs_date ON public.sewing_jobs USING btree (date DESC)                                                                                        |
| public     | sewing_jobs     | idx_jobs_delivery_expected     | CREATE INDEX idx_jobs_delivery_expected ON public.sewing_jobs USING btree (delivery_date_expected) WHERE (delivery_date_expected IS NOT NULL)                   |
| public     | sewing_jobs     | idx_jobs_status                | CREATE INDEX idx_jobs_status ON public.sewing_jobs USING btree (status)                                                                                         |
| public     | sewing_jobs     | idx_jobs_status_date           | CREATE INDEX idx_jobs_status_date ON public.sewing_jobs USING btree (status, date DESC) WHERE (status = ANY (ARRAY['Pending'::job_status, 'Part'::job_status])) |
| public     | sewing_jobs     | idx_sewing_jobs_customer       | CREATE INDEX idx_sewing_jobs_customer ON public.sewing_jobs USING btree (customer_id)                                                                           |
| public     | sewing_jobs     | idx_sewing_jobs_date           | CREATE INDEX idx_sewing_jobs_date ON public.sewing_jobs USING btree (date)                                                                                      |
| public     | sewing_jobs     | idx_sewing_jobs_status         | CREATE INDEX idx_sewing_jobs_status ON public.sewing_jobs USING btree (status)                                                                                  |